----------------------------------------------------------------------
-- BASE DE DATOS : Matricula
----------------------------------------------------------------------

USE MASTER
GO
--
IF EXISTS(SELECT NAME FROM MASTER..sysdatabases where name='Matricula')   	
	DROP DATABASE MATRICULA
GO

CREATE DATABASE MATRICULA
ON PRIMARY(
	NAME = 'Matricula_data',
	FILENAME = 'D:\DB\Matricula_Data.mdf',
	SIZE = 20 MB, 
	MAXSIZE = 50 MB,
	FILEGROWTH = 10%
)LOG ON(
	NAME = 'SysMedic_log',
	FILENAME = 'D:\DB\Matricula_Log.ldf', 
	SIZE = 20 MB,
	FILEGROWTH = 2MB
)
GO
--
USE MATRICULA;
GO
--
-- D I S T R I T OS
--
CREATE TABLE DISTRITO(
ID_DIS INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOM_DIS VARCHAR(50)
)

INSERT INTO DISTRITO VALUES('Cartago'),
						('Oriental'),
						('Occidental'),
						('Paraiso'),
						('Zapote')
--
-- P O S I C I O N -
--
CREATE TABLE POSICION(
ID_POSI INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOM_POSI VARCHAR(35)
)

INSERT INTO POSICION VALUES('Administrativo'),('Docente'),('Alumno')
--
-- P E R S O N A
--
CREATE TABLE PERSONA (
ID_PERSO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOM_PERSO VARCHAR(60),
APE_PERSO VARCHAR(60),
TELEFONO VARCHAR(9),
FOTO IMAGE,
DNI VARCHAR(8),
EMAIL VARCHAR(70),
SEXO CHAR(1),
FECHA_NAC DATE,
EST_PERSO CHAR(1),
DIRRECION VARCHAR(60),
ID_DIS INT REFERENCES DISTRITO(ID_DIS),
NIVEL VARCHAR(15)
)

INSERT INTO PERSONA VALUES('Brian','Torres', '972101160',NULL,'72816121','bryan98tm@gmail.com','M','1998-06-29','A','MZ T Lt 1-A',1,'Alumno'),
						  ('Abigail','Neyra','958594223',NULL,'12345678','GianinaNeyraAL@gmail.com','F','1998-06-09','A','Angamos',7,'Alumno'),
						  ('Jhon','Valverde', '951753852',NULL,'12345678','jhon98@gmail.com','M','2000-01-20','A','MZ T Lt 1-A',2,'Alumno'),
						  ('Damaris','Camalgo', '995979223',NULL,'3216547','damaris22@gmail.com','F','1995-07-12','A','MZ T Lt 1-A',3,'Alumno'),
						  ('Karen','Pachon', '987654321',NULL,'7418222','karen@gmail.com','F','1998-11-01','A','',1,'Alumno'),
						  ('Prur6bas#1','Prubeba!', '123456789',NULL,'1234567','1234567@gmail.com','M','1998-06-29','A','MZ T Lt 1-A',5,'Alumno'),
						  ('Maestro1','Maestro1', '123456789',NULL,'1234567','maestro1@gmail.com','M','1998-06-29','A','MZ T Lt 1-A',4,'Maestro'),
						  ('Maestro2','Maestro2', '123456789',NULL,'1234567','maestro2@gmail.com','M','1800-07-29','A','MZ T Lt 1-A',2,'Maestro'),
						  ('Admin','admin', '987654321',NULL,'1234567','admin@gmail.com','F','1980-12-20','A','MZ T Lt 1-A',3,'Administrativo')
--
-- A P O D E R A D O
--
CREATE TABLE APODERADO(
ID_APODE INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOM_APODE VARCHAR(60),
APELLIDO VARCHAR(60),
PARENTEZCO VARCHAR(30),
DNI VARCHAR(8),
FECHA_NAC DATE,
TELF_APOR VARCHAR(9),
EST_CIVIL VARCHAR(25),
DIRRECION VARCHAR(60),
SEXO CHAR(1),
ID_DIS INT
FOREIGN KEY (ID_DIS) REFERENCES DISTRITO(ID_DIS)
)

INSERT INTO APODERADO VALUES('Juan', 'Torres', 'Padre','12345678' , '12-07-1969','995509218','S','AAHH Mateo Pumacahua','M',1),
							('Reyna', 'Menacho', 'Abuela','12345678', '08-04-1972','995979223','S','AAHH Mateo Pumacahua','M',1),
							('Pablo', 'Escobar', 'Tio','12345678','12-01-1991','123456789','D','AAHH Mateo Pumacahua','M',3),
							('Dionica', 'Valverde', 'Abuela','12345678' ,'11-11-1950','995509218','C','AAHH Mateo Pumacahua','M',5),
							('Juan', 'Torres', 'Padre','12345678', '01-12-1998','972101160','V','AAHH Mateo Pumacahua','M',2),
							('PRactica', 'PRactica', 'Padre','12345678','01-12-1998','972101160','V','AAHH Mateo Pumacahua','M',2)							
--
-- U S U A R I O
--
CREATE TABLE USUARIO(
ID_USU INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOM_USU VARCHAR(30),
PASS VARCHAR(30),
POSICION VARCHAR(15)
)

INSERT INTO USUARIO VALUES--('BTORRESM98','123',3),
						 --('ANEYRAF98','123',3),
						 --('JVALVERDE00','123',3),
						 --('DCAMA66LGO95','123',3),
						 --('KPACHON98','123',3),
						 --('PPRUEBA98','123',3),
						 --('Maestro1', '123', 2),
						 --('Maestro2','123',2),
						('Admin', '123', 'Administrativo')
--
-- C A R R E R A
--
CREATE TABLE CARRERA(
ID_CARRERA INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOM_CARRERA VARCHAR(40)
)

INSERT INTO CARRERA VALUES('Ingeneria Sistemas'),
						  ('Ingeneria Software'),
						  ('Ingeneria Civil'),
						  ('Ingeneria Ambiental'),
						  ('Ingeneria Indusltrial'),
						  ('Derecho'),
						  ('Psicologia'),
						  ('Administracion de Empresas'),('Medicina')
--
-- A L U M N O
--
CREATE TABLE ALUMNO (
ID_ALUM INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ID_APODE INT,
COD_ALUM VARCHAR(25),
ID_PERSO INT,
ID_CARRERA INT,
ID_USU INT
FOREIGN KEY (ID_APODE) REFERENCES APODERADO(ID_APODE) ON DELETE CASCADE,
FOREIGN KEY (ID_PERSO) REFERENCES PERSONA(ID_PERSO) ON DELETE CASCADE, 
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA),
FOREIGN KEY (ID_USU) REFERENCES USUARIO(ID_USU)
)

INSERT INTO ALUMNO VALUES(1,'BTORRESM98',1,1,2),
						 (2,'ANEYRAF98',2,2,5),
						 (3,'JVALVERDE00',3,3,1),
						 (4,'DCAMALGO95',4,4,8),
						 (5,'KPACHON98',5,5,4),
						 (6,'PPRUEBA98',6,6,7)
--
-- E M P L E A D O
--
CREATE TABLE EMPLEADO(
ID_EMPLEADO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
COD_EMPLE VARCHAR(25),
ID_PERSO INT,
SUELDO_BASE FLOAT,
HORAS_TRABAJO TIME,
FOREIGN KEY(ID_PERSO) REFERENCES PERSONA(ID_PERSO) ON DELETE CASCADE
)

INSERT INTO EMPLEADO VALUES('MM198', 6, 930.50, '8:30'),
						   ('MM200', 7, 1200.50, '4:00'),
						   ('AA80', 8, 1350, '8:00')
--
-- A D M I N I S T R A T I V O
--
CREATE TABLE ADMINISTRATIVO(
ID_ADMIN INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ID_EMPLEADO INT,
CARGO VARCHAR(25),
DEPARTAMENTO VARCHAR(30),
ID_USU INT
FOREIGN KEY (ID_USU) REFERENCES USUARIO(ID_USU) ON DELETE CASCADE,
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO) ON DELETE CASCADE
)

INSERT INTO ADMINISTRATIVO VALUES(3, 'Director Academico', 'Facultad de Ingeneria', 8)
--
-- M A E S T R O
--
CREATE TABLE MAESTRO(
ID_MAESTRO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ID_EMPLEADO INT,
AREA_DOCEN VARCHAR(50),
ID_USU INT
FOREIGN KEY (ID_USU) REFERENCES USUARIO(ID_USU) ON DELETE CASCADE,
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO) ON DELETE CASCADE
)

INSERT INTO MAESTRO VALUES(1, 'Computacion e Informatica', 6),
						  (2, 'Administrador de Base de Datos', 7)
--------------------
-- C I C L O S
------------------
CREATE TABLE CICLO(
ID_CICLO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOM_CICLO VARCHAR(10)
)
INSERT INTO CICLO VALUES('I'),
						('II'),
						('III'),
						('IV'),
						('V'),
						('VI'),
						('VII'),
						('VIII'),
						('IX'),
						('X')
--
-- C U R S O S
--
CREATE TABLE CURSOS(
ID_CURSO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOM_CURSO VARCHAR(100),
ID_CARRERA INT,
ID_CICLO INT
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA),
FOREIGN KEY (ID_CICLO) REFERENCES CICLO(ID_CICLO)
)

INSERT INTO CURSOS VALUES('Software Aplicativo',1,1),
						('Fundamentos de la Programacion',1,1),
						('Matematica 1',1,1),
						('Tecnologias Web',1,1),
						('Base de Datos',1,1)
INSERT INTO CURSOS VALUES('Introduccion a la Ingeneria',2,1),
						('Introduccion a la Matematica',2,1),
						('Quimica General',2,1),
						('Comprension y Redaccion de Textos',2,1),
						('Investigacion Academica',2,1)
INSERT INTO CURSOS VALUES('Introduccion a la Ingeneria',3,1),
						('Introduccion a la Matematica',3,1),
						('Quimica General',3,1),
						('Comprension y Redaccion de Textos',3,1),
						('Investigacion Academica',3,1)
INSERT INTO CURSOS VALUES('Introduccion a la Ingeneria',4,1),
						('Introduccion a la Matematica',4,1),
						('Quimica General',4,1),
						('Comprension y Redaccion de Textos',4,1),
						('Investigacion Academica',4,1)
INSERT INTO CURSOS VALUES('Introduccion a la Ingeneria',5,1),
						('Introduccion a la Matematica',5,1),
						('Quimica General',5,1),
						('Comprension y Redaccion de Textos',5,1),
						('Investigacion Academica',5,1)
INSERT INTO CURSOS VALUES('Introduccion a la Ingeneria',6,1),
						('Introduccion a la Matematica',6,1),
						('Quimica General',6,1),
						('Comprension y Redaccion de Textos',6,1),
						('Investigacion Academica',6,1)
INSERT INTO CURSOS VALUES('Introduccion a la Ingeneria',7,1),
						('Introduccion a la Matematica',7,1),
						('Quimica General',7,1),
						('Comprension y Redaccion de Textos',7,1),
						('Investigacion Academica',7,1)
INSERT INTO CURSOS VALUES('Introduccion a la Ingeneria',8,1),
						('Introduccion a la Matematica',8,1),
						('Quimica General',8,1),
						('Comprension y Redaccion de Textos',8,1),
						('Investigacion Academica',8,1)
--
-- C L A S E S
--
CREATE TABLE CLASE(
ID_CLASE INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ID_CARRERA INT,
HORA_SEMAN FLOAT,
VACANTES INT
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA) ON DELETE CASCADE
)

INSERT INTO CLASE VALUES(1, 18, 20),
						(1, 18, 20),
						(1, 18, 20),
						(1, 18, 20),
						(1, 18, 20)
--
-- S E C C I O N
--
CREATE TABLE SECCION(
ID_SECCION INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
COD_SECCION VARCHAR(10),
ID_CLASE INT
FOREIGN KEY (ID_CLASE) REFERENCES CLASE(ID_CLASE)
)

INSERT INTO SECCION VALUES('PDSDS-301', 1),
						  ('PDSDS-302', 1),
						  ('PDSDS-303', 1),
						  ('PDSDS-304', 1),
						  ('PDSDS-305', 1)
-----------------------
-- M A T R I C U L A --
-----------------------
CREATE TABLE MATRICULA(
ID_MATRIC INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ID_ALUM INT,
TURNO VARCHAR(15),
PERIODO VARCHAR(10),
ID_SECCION INT REFERENCES SECCION(ID_SECCION),
ID_CICLO INT,
FECHA DATE
FOREIGN KEY(ID_ALUM) REFERENCES ALUMNO(ID_ALUM),
FOREIGN KEY(ID_CICLO) REFERENCES CICLO(ID_CICLO)
)
SELECT * FROM MATRICULA
INSERT MATRICULA VALUES(1, 1, 14.5),
					   (2, 1, 18.0),
					   (3, 1, 11.5),
					   (4, 1, 17.6),
					   (5, 1, 14.5)		
					   EXEC LISTAR_ALUM_NOMATRI
--------------------------------
-- C L A S E S  C R E A D A S --
--------------------------------
CREATE TABLE CLASES_CREADAS(
ID_CCREADAS INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ID_MAESTRO INT,
ID_MATRIC INT,
ID_SECCION INT
FOREIGN KEY(ID_MATRIC)REFERENCES MATRICULA(ID_MATRIC) ON DELETE CASCADE,
FOREIGN KEY(ID_MAESTRO)REFERENCES MAESTRO(ID_MAESTRO) ON DELETE CASCADE,
FOREIGN KEY(ID_SECCION) REFERENCES SECCION(ID_SECCION) ON DELETE CASCADE
)

INSERT INTO CLASES_CREADAS VALUES(1, 1, 1)
GO
--
-- P R O C E D I M I E N T O S  A L M A C E N A D O S
--
-------------------------
-- Copia de Seguridad --
-------------------------
CREATE PROCEDURE COPIADB
@DB VARCHAR(30),
@ETIQ VARCHAR(30),
@TIPO BIT
AS
	DECLARE @SQL VARCHAR(100)
	SET @SQL = 'BACKUP DATABASE ' + @DB + ' TO DISK = ' + CHAR(39) + 'D:\DB\' + @ETIQ + '.BAK' + CHAR(39)
	IF(@TIPO = 1)
		SET @SQL = @SQL + ' WITH DIFFERENTIAL'
	EXEC (@SQL)
GO

EXEC COPIADB 'MATRICULA', 'COMPLETO', 0
GO
-------------------
-- Restaurar una Base de Datos
CREATE PROCEDURE RESTOREDB
@NOMDB VARCHAR(25),
@COPIA VARCHAR(25)
AS
	DECLARE @SQL VARCHAR(100)
	EXEC('USE MASTER')
	EXEC('DROP DATABASE ' + @NOMDB)
	SET @SQL = 'RESTORE DATABASE ' + @NOMDB + ' FROM DISK = ' + CHAR(39) + 'D:\DB\' + @COPIA + '.BAK' + CHAR(39);
	EXEC (@SQL);
GO

EXEC RESTOREDB 'Matricula','MatCompl13-10'
GO
-----------------

--
-- L I S T A D O
--
--------------------
-- Listar Alumnos --
--------------------
CREATE PROCEDURE LISTAR_ALUM
AS 
	SELECT A.ID_ALUM, A.COD_ALUM, P.NOM_PERSO, P.APE_PERSO, C.NOM_CARRERA, 
	AP.NOM_APODE, AP.PARENTEZCO, P.TELEFONO, P.EMAIL, P.SEXO, P.EST_PERSO 
	FROM ALUMNO A
	INNER JOIN PERSONA P
	ON A.ID_PERSO = P.ID_PERSO
	INNER JOIN CARRERA C
	ON A.ID_CARRERA = C.ID_CARRERA
	INNER JOIN APODERADO AP
	ON A.ID_APODE = AP.ID_APODE
	INNER JOIN DISTRITO D
	ON D.ID_DIS = P.ID_DIS 
	INNER JOIN MATRICULA M
	ON A.ID_ALUM = M.ID_ALUM
GO

EXEC LISTAR_ALUM
GO
-------------
-- Listar Alumnos no Matriculados
-----------
CREATE PROCEDURE LISTAR_ALUM_NOMATRI
AS
	SELECT A.ID_ALUM, A.COD_ALUM, P.NOM_PERSO, P.APE_PERSO, C.NOM_CARRERA, P.DNI, P.FECHA_NAC,
	AP.NOM_APODE, AP.PARENTEZCO, P.TELEFONO, P.EMAIL, P.SEXO, P.DIRRECION, D.NOM_DIS, EST_PERSO
	FROM ALUMNO A
	LEFT JOIN PERSONA P
	ON A.ID_PERSO = P.ID_PERSO
	LEFT JOIN APODERADO AP
	ON A.ID_APODE = AP.ID_APODE
	LEFT JOIN DISTRITO D
	ON D.ID_DIS = P.ID_DIS 
	LEFT JOIN MATRICULA M
	ON A.ID_ALUM = M.ID_ALUM 
	LEFT JOIN CARRERA C 
	ON C.ID_CARRERA = A.ID_CARRERA
	WHERE M.ID_MATRIC IS NULL					
GO

EXEC LISTAR_ALUM_NOMATRI
GO
----------------------
-- Listar Empleados --
----------------------
CREATE PROCEDURE LISTAR_EMPLE
AS
	SELECT  E.ID_EMPLEADO AS ID, E.COD_EMPLE AS COD, P.NOM_PERSO AS Nombre, P.APE_PERSO AS Apellido, P.DNI AS DNI, P.EMAIL AS Email, P.FECHA_NAC AS Fecha, 
	P.SEXO AS Sexo, P.TELEFONO AS Celular, E.HORAS_TRABAJO AS Horas, E.SUELDO_BASE AS Sueldo, P.EST_PERSO AS Estado
	FROM EMPLEADO E
	INNER JOIN PERSONA P
	ON E.ID_PERSO = P.ID_PERSO
GO

EXEC LISTAR_EMPLE
GO
---------------------
-- Listar Maestros --
---------------------
CREATE PROCEDURE LISTAR_MAEST
AS
	SELECT M.ID_MAESTRO, E.COD_EMPLE, P.NOM_PERSO, P.APE_PERSO, M.AREA_DOCEN, P.SEXO
	FROM MAESTRO M
	INNER JOIN EMPLEADO E
	ON M.ID_EMPLEADO = E.ID_EMPLEADO
	INNER JOIN PERSONA P
	ON E.ID_PERSO = P.ID_PERSO
GO

EXEC LISTAR_MAEST
GO
---------------------------
-- Listar Administrativos--
---------------------------
CREATE PROCEDURE LISTAR_ADMIN
AS
	SELECT A.ID_ADMIN, E.COD_EMPLE, P.NOM_PERSO, P.APE_PERSO, P.SEXO, A.CARGO, A.DEPARTAMENTO
	FROM ADMINISTRATIVO A
	INNER JOIN EMPLEADO E
	ON A.ID_EMPLEADO = E.ID_EMPLEADO
	INNER JOIN PERSONA P
	ON E.ID_PERSO = P.ID_PERSO
GO

EXEC LISTAR_ADMIN
GO
------------
-- Listar Usuario de Inicio de Sesion
------------
CREATE PROCEDURE INICIAR_SESION
@USER VARCHAR(25),
@CONTRA VARCHAR(30)
AS
	SELECT U.*, P.FOTO
	FROM USUARIO U 
	INNER JOIN ALUMNO A
	ON U.ID_USU = A.ID_USU
	INNER JOIN PERSONA P
	ON P.ID_PERSO = A.ID_PERSO
	WHERE U.NOM_USU = @USER AND U.PASS = @CONTRA
GO

EXEC INICIAR_SESION 'BTORRESM98','123'
GO
--
CREATE PROCEDURE MAEST
@USER VARCHAR(25)
AS
	SELECT U.*, P.FOTO
	FROM USUARIO U
	INNER JOIN MAESTRO M
	ON U.ID_USU = M.ID_USU
	INNER JOIN EMPLEADO E
	ON M.ID_EMPLEADO = E.ID_EMPLEADO
	INNER JOIN PERSONA P
	ON E.ID_PERSO = P.ID_PERSO
	WHERE U.NOM_USU = @USER
GO

EXEC MAEST 'MM198'
GO

--
CREATE PROCEDURE ADMINIS
@USER VARCHAR(25)
AS
	SELECT U.*, P.FOTO
	FROM USUARIO U
	INNER JOIN ADMINISTRATIVO AD
	ON U.ID_USU = AD.ID_USU
	INNER JOIN EMPLEADO E
	ON AD.ID_EMPLEADO = E.ID_EMPLEADO
	INNER JOIN PERSONA P
	ON P.ID_PERSO = E.ID_PERSO
	WHERE U.NOM_USU = @USER
GO
--------
CREATE PROCEDURE DATOS_USER
@COD VARCHAR(25)
AS
	SELECT P.NOM_PERSO, P.APE_PERSO 
	FROM PERSONA P
	INNER JOIN ALUMNO A
	ON A.ID_PERSO = P.ID_PERSO
	INNER JOIN EMPLEADO E
	ON E.ID_PERSO = E.ID_PERSO
GO
--
--------------------------------------
-- Listar Ultimo Apoderado Ingresado --
--------------------------------------
CREATE PROCEDURE ULTIMA_APODE
AS
	SELECT TOP 1 ID_APODE, NOM_APODE FROM APODERADO ORDER BY ID_APODE DESC
GO

EXEC ULTIMA_APODE
GO
-------------------------------------
-- Listar los Apoderados Sin Alumno --
-------------------------------------
CREATE PROCEDURE APODE_SIN
AS
	SELECT APO.ID_APODE, APO.NOM_APODE
	FROM ALUMNO A RIGHT JOIN APODERADO APO
	ON APO.ID_APODE = A.ID_APODE
	WHERE A.ID_ALUM IS NULL
GO

EXEC APODE_SIN
GO
-----------------
-- Listar Cursos POR CODIGO
-------------
CREATE PROCEDURE LISTAR_CURSOS
@COD VARCHAR(20)
AS
	SELECT CI.NOM_CICLO, CU.NOM_CURSO
	FROM ALUMNO A
	INNER JOIN CARRERA CA
	ON A.ID_CARRERA = CA.ID_CARRERA
	INNER JOIN CURSOS CU
	ON CA.ID_CARRERA = CU.ID_CARRERA
	INNER JOIN CICLO CI
	ON CU.ID_CICLO = CI.ID_CICLO
	WHERE A.COD_ALUM = @COD
GO

EXEC LISTAR_CURSOS 'ANEYRAF98'
GO
--
--
--
CREATE PROCEDURE LISTAR_USU
AS
	SELECT ID_USU, NOM_USU, PASS, POSICION FROM USUARIO 
GO
--
-- I N S E R C I O N
--
------------------------
-- Ingresar Apoderado --
------------------------
CREATE PROCEDURE ING_APO
	@NOM VARCHAR(60),
	@APE VARCHAR(60),
	@PAREN VARCHAR(30),
	@DNI VARCHAR(8),
	@NAC DATE,
	@TELF VARCHAR(9),
	@EST VARCHAR(25),
	@DIREC VARCHAR(60),
	@SEXO CHAR(1),
	@DISTRI INT
AS
	INSERT INTO APODERADO VALUES(@NOM, @APE, @PAREN, @DNI, @NAC, @TELF, @EST, @DIREC, @SEXO, @DISTRI)
GO

EXEC ING_APO 'Apode1','Apode','Madre','12345678','1998-01-20','995979223','Soltero','AAHH Mateo Pumacahua','F',5
GO
-----------------------
-- Ingresar Personas --
-----------------------
create PROCEDURE ING_PER
	@IDPER INT OUTPUT,
	@NOM VARCHAR(60),
	@APE VARCHAR(60),
	@TELF VARCHAR(9),
	@FOTO IMAGE,
	@DNI VARCHAR(8),
	@EMAIL VARCHAR(70),
	@SEXO CHAR(1),
	@NAC DATE,
	@EST CHAR(1),
	@DIREC VARCHAR(60),
	@IDDIS INT,
	@NIVEL VARCHAR(25)
AS 
	INSERT INTO PERSONA VALUES(@NOM, @APE, @TELF, @FOTO, @DNI, @EMAIL, @SEXO, @NAC, @EST, @DIREC, @IDDIS, @NIVEL)
	SET @IDPER = SCOPE_IDENTITY()
GO 

EXEC ING_PER 0,'Alan','Garcia','995509218',NULL,'12345678','alan@gmail.com','M','1986-01-20','A','asdasd',1,'Alumno'
EXEC ING_PER 0,'Juan','Lee','934626785',NULL,'12345678','alan@gmail.com','F','1986-01-20','A','asdasd',1,'Docente'
EXEC ING_PER 0,'Anthony','Menacho',NULL,'972101160','12345678','alan@gmail.com','M','1986-01-20','A','asdasd',1,'Alumno'
GO
---------------------
-- Ingresar Alumno --
---------------------
CREATE PROCEDURE INSER_ALUM
@IDAPODE INT,
@IDPERSO INT
AS
	INSERT INTO ALUMNO VALUES(@IDAPODE, NULL, @IDPERSO, NULL, NULL)
GO

EXEC INSER_ALUM 7,10
EXEC INSER_ALUM 9,14
GO
----------------
-- Ingresar Empleado
-------------
CREATE PROCEDURE INSER_EMP
	@IDEMPLE INT OUTPUT,
	@IDPERSO INT,
	@SUELDO FLOAT,
	@HORAS DATETIME
AS 
	INSERT INTO EMPLEADO VALUES(NULL, @IDPERSO, @SUELDO, @HORAS)
	SET @IDEMPLE = SCOPE_IDENTITY()
GO

EXEC INSER_EMP 0, 9, 1250,'08:00:00'
EXEC INSER_EMP 0, 10, 1500,'04:00:00'
GO
----------------------
-- Ingresar Maestro --
----------------------
CREATE PROCEDURE INSER_MAES
	@IDEMPLE INT,
	@AREDOC VARCHAR(30),
	@IDUSU INT
AS
	INSERT INTO MAESTRO VALUES(@IDEMPLE, @AREDOC, @IDUSU)
GO

INSERT INTO USUARIO values ('Java','123','admin')

EXEC INSER_MAES 3, 'Programador C# ', 9
GO
-----------------------------
-- Insertar Administrativo --
-----------------------------
CREATE PROCEDURE INSER_ADMINIS
	@IDEMP INT,
	@CARGO VARCHAR(20),
	@DEPAR VARCHAR(50),
	@IDUSU INT
AS
	INSERT INTO ADMINISTRATIVO VALUES(@IDEMP, @CARGO, @DEPAR, @IDUSU)
GO

INSERT INTO USUARIO VALUES ('director','123','admin')

EXEC INSER_ADMINIS 9,'Director','Administrativo', 10
GO
--
-- M O D I F I C A R
--
----------------------
-- Modificar Alumno --
----------------------
CREATE PROCEDURE MODF_ALUM
	@ID INT,
	@NOM VARCHAR(60),
	@APE VARCHAR(60),
	@TELF VARCHAR(9),
	@DNI VARCHAR(8),
	@EMAIL VARCHAR(70),
	@SEXO CHAR(1),
	@NAC DATE,
	@EST CHAR(1),
	@DIREC VARCHAR(60),
	@IDDIS INT,
	@FOTO IMAGE
AS
	UPDATE PERSONA SET NOM_PERSO = @NOM, APE_PERSO = @APE, TELEFONO = @TELF, DNI = @DNI, EMAIL = @EMAIL, SEXO = @SEXO, FECHA_NAC = @NAC, EST_PERSO = @EST, DIRRECION = @DIREC, ID_DIS = @IDDIS, FOTO = @FOTO WHERE ID_PERSO = @ID
GO

EXEC MODF_ALUM 1,'Modificado1','ApeModificado1','123456789','12345678','corremodificado@gmail.com','M','1998-06-29','A','Mz T Lt 1-A', 3
GO
--
-- E L I M I N A R
--
-------------
--
---------------
CREATE PROCEDURE ELIMINAR
AS

GO
--
-- B U S Q U E D A S
--
--------------------
-- Buscar Alumnos --
--------------------
CREATE PROCEDURE BUSCAR_ALUM
@COD VARCHAR(15)
AS
	SELECT P.ID_PERSO, A.ID_ALUM, A.COD_ALUM, P.NOM_PERSO, C.NOM_CARRERA, P.APE_PERSO, P.DNI, P.FECHA_NAC,
	AP.NOM_APODE, AP.PARENTEZCO, P.TELEFONO, P.EMAIL, P.SEXO, P.DIRRECION, D.NOM_DIS, EST_PERSO, P.FOTO
	FROM ALUMNO A
	INNER JOIN PERSONA P
	ON A.ID_PERSO = P.ID_PERSO
	INNER JOIN CARRERA C
	ON A.ID_CARRERA = C.ID_CARRERA
	INNER JOIN CURSOS CU
	ON C.ID_CARRERA = CU.ID_CARRERA
	INNER JOIN APODERADO AP
	ON A.ID_APODE = AP.ID_APODE
	INNER JOIN DISTRITO D
	ON D.ID_DIS = P.ID_DIS
	WHERE A.COD_ALUM = @COD
GO

EXEC BUSCAR_ALUM 'BTORRES98'
GO
---------------
-- Buscar
-----------------
CREATE PROCEDURE BUSCAR_ALUMD
	@NUM int,
	@COD VARCHAR(15),
	@APE VARCHAR(15)
AS
	DECLARE @CONSULTA VARCHAR(800)
	SET @CONSULTA = 'SELECT A.ID_ALUM, A.COD_ALUM, P.NOM_PERSO, P.APE_PERSO, P.DNI, P.FECHA_NAC,
					AP.NOM_APODE, AP.PARENTEZCO, P.TELEFONO, P.EMAIL, P.SEXO, P.DIRRECION, D.NOM_DIS, EST_PERSO
					FROM ALUMNO A
					INNER JOIN PERSONA P
					ON A.ID_PERSO = P.ID_PERSO
					INNER JOIN APODERADO AP
					ON A.ID_APODE = AP.ID_APODE
					INNER JOIN DISTRITO D
					ON D.ID_DIS = P.ID_DIS 
					INNER JOIN MATRICULA M
					ON A.ID_ALUM = M.ID_ALUM 
					WHERE '
	/*IF @APE = '' AND @COD = ''
		EXEC LISTAR_ALUM
	ELSE
		BEGIN*/
			IF @num = 1
				SET @CONSULTA = @CONSULTA + ' A.COD_ALUM LIKE ' + CHAR(39) + @COD + '%' + CHAR(39)
			ELSE
				SET @CONSULTA = @CONSULTA + ' P.APE_PERSO LIKE ' + CHAR(39) + @APE + '%' + CHAR(39)
			EXEC (@CONSULTA)
		/*END*/
GO
					
EXEC BUSCAR_ALUMD 7,'',''
GO

-- 
-- T R I G G E R S
--
--------------------------------------------
-- Trigger para insertar Codigo de Alumno --
--------------------------------------------
CREATE TRIGGER CODIGO
ON PERSONA FOR INSERT
AS
	DECLARE @APODE INT, @IDPERSO INT, @NOM CHAR(1), @APE VARCHAR(25), @FECHA CHAR(2), @CODALUM VARCHAR(15), @NIVEL VARCHAR(15)
	SET @APODE = (SELECT TOP 1 ID_APODE FROM APODERADO ORDER BY ID_APODE DESC)
	SELECT @IDPERSO = ID_PERSO,  @NOM = LEFT(NOM_PERSO, 1),  @APE = APE_PERSO,  @FECHA = RIGHT(YEAR(FECHA_NAC),2), @NIVEL = NIVEL FROM INSERTED
	IF(@NIVEL = 'Alumno') 
		INSERT INTO ALUMNO VALUES(@APODE, UPPER(CONCAT(@NOM,@APE,@FECHA)), @IDPERSO, NULL, NULL) 
	ELSE
		IF(@NIVEL = 'Docente')
		BEGIN
			SET @APE = LEFT(@APE, 1)
			INSERT INTO EMPLEADO VALUES(UPPER(CONCAT(@NOM,@APE,@FECHA)), @IDPERSO, NULL, NULL)
		END
GO
--
CREATE TRIGGER TR_VACAN
ON MATRICULA FOR INSERT
AS
	DECLARE @VAC INT, @ID INT
	SELECT @ID = ID_SECCION FROM inserted
	UPDATE C SET VACANTES = (VACANTES - 1) FROM CLASE C 
	INNER JOIN SECCION S 
	ON C.ID_CLASE = S.ID_CLASE
	WHERE S.ID_SECCION = @ID
GO

SELECT * FROM MATRICULA
SELECT * FROM SECCION
select * from CLASE
SELECT * FROM CLASES_CREADAS
GO
--
--
CREATE PROCEDURE ING_MATRICU
@IDALU INT,
@TURNO VARCHAR(20),
@PERIODO VARCHAR(15),
@IDSECCION INT,
@IDCICLO INT,
@FECHA DATE
AS
	INSERT INTO MATRICULA VALUES(@IDALU, @TURNO, @PERIODO, @IDSECCION, @IDCICLO, @FECHA)
GO
SELECT * FROM SECCION
select * from CLASE
SELECT * FROM MATRICULA
select * from ALUMNO
EXEC LISTAR_ALUM_NOMATRI
EXEC ING_MATRICU 3,1,'Mañana','2019-02', 2,''
GO
--
CREATE PROCEDURE ACTUALIZAR_ALUM
@DATO INT,
@IDPERSO INT
AS
	UPDATE A SET A.ID_CARRERA = @DATO FROM ALUMNO A
	INNER JOIN PERSONA P 
	ON P.ID_PERSO = A.ID_PERSO
	WHERE A.ID_PERSO = @IDPERSO
GO
SELECT * FROM PERSONA
SELECT * FROM ALUMNO
EXEC LISTAR_ALUM_NOMATRI
EXEC ACTUALIZAR_ALUM 1, 12
GO
--
create PROCEDURE ACTUALIZAR_EMPLE
@idemple int output,
@SUELDO FLOAT,
@HORAS VARCHAR(15),
@IDPERSO INT
AS
	UPDATE E SET E.SUELDO_BASE = @SUELDO, E.HORAS_TRABAJO = @HORAS 
	FROM EMPLEADO E
	INNER JOIN PERSONA P 
	ON P.ID_PERSO = E.ID_EMPLEADO
	WHERE E.ID_PERSO = @IDPERSO
	set @idemple = @@IDENTITY
GO

EXEC ACTUALIZAR_EMPLE 0,1500.00, '12:00', 6
GO
--
CREATE PROCEDURE BUSCAR_EMPLEID
@COD VARCHAR(15)
AS
	SELECT P.ID_PERSO, E.COD_EMPLE, P.NOM_PERSO, P.APE_PERSO, P.TELEFONO, P.FOTO, P.DNI, P.EMAIL, P.SEXO,
	P.FECHA_NAC, P.DIRRECION, D.NOM_DIS, E.SUELDO_BASE, E.HORAS_TRABAJO FROM PERSONA P
	INNER JOIN DISTRITO D
	ON P.ID_DIS = D.ID_DIS
	INNER JOIN EMPLEADO E
	ON P.ID_PERSO = E.ID_PERSO
	WHERE E.COD_EMPLE = @COD
GO

EXEC BUSCAR_EMPLEID 'RH69'
GO
--
CREATE PROCEDURE ING_MAESTRO
@IDEMPLE INT,
@AREADOCEN VARCHAR(50)
AS
	INSERT INTO MAESTRO VALUES(@IDEMPLE, @AREADOCEN, NULL)
GO
--
CREATE PROCEDURE LIS_SECCION
AS
	SELECT S.ID_SECCION, S.COD_SECCION, C.VACANTES FROM SECCION S
	INNER JOIN CLASE C
	ON S.ID_CLASE = C.ID_CLASE
GO
--
select * from PERSONA
select * from EMPLEADO
select * from MAESTRO

select * from APODERADO
select * from PERSONA
select * from ALUMNO
SELECT * FROM MATRICULA GO
create PROCEDURE LISTAR_MATRI
@IDALUM INT
AS
	SELECT A.COD_ALUM, P.NOM_PERSO, P.APE_PERSO, P.DNI, CA.NOM_CARRERA, P.TELEFONO, P.EMAIL, M.TURNO, M.PERIODO, S.COD_SECCION, C.NOM_CICLO FROM MATRICULA M
	INNER JOIN ALUMNO A
	ON M.ID_ALUM = A.ID_ALUM
	INNER JOIN PERSONA P
	ON P.ID_PERSO = A.ID_PERSO
	INNER JOIN SECCION S
	ON M.ID_SECCION = S.ID_SECCION
	INNER JOIN CICLO C 
	ON M.ID_CICLO = C.ID_CICLO
	INNER JOIN CARRERA CA
	ON A.ID_CARRERA = CA.ID_CARRERA
	WHERE A.ID_ALUM = @IDALUM
GO
--
CREATE PROCEDURE LISTARCURS
@IDALUM INT
AS
	SELECT CU.NOM_CURSO FROM ALUMNO A
	INNER JOIN CARRERA C
	ON A.ID_CARRERA = C.ID_CARRERA
	INNER JOIN CURSOS CU
	ON C.ID_CARRERA = CU.ID_CARRERA
	WHERE A.ID_ALUM =1 
GO
--
create PROCEDURE matri
@IDALUM INT,
@CARRE INT
AS
	SELECT A.COD_ALUM, P.NOM_PERSO, P.APE_PERSO, P.DNI, CA.NOM_CARRERA, P.TELEFONO, P.EMAIL, M.TURNO, M.PERIODO, S.COD_SECCION, C.NOM_CICLO, CU.NOM_CURSO FROM MATRICULA M
	INNER JOIN ALUMNO A
	ON M.ID_ALUM = A.ID_ALUM
	INNER JOIN PERSONA P
	ON P.ID_PERSO = A.ID_PERSO
	INNER JOIN SECCION S
	ON M.ID_SECCION = S.ID_SECCION
	INNER JOIN CICLO C 
	ON M.ID_CICLO = C.ID_CICLO
	INNER JOIN CARRERA CA
	ON A.ID_CARRERA = CA.ID_CARRERA
	INNER JOIN CURSOS CU
	ON Ca.ID_CARRERA = CU.ID_CARRERA
	WHERE A.ID_ALUM = @IDALUM and CA.ID_CARRERA =  @CARRE
GO
--

--
CREATE TRIGGER USU
ON USUARIO FOR INSERT
AS
	DECLARE @COD VARCHAR(15), @POSI VARCHAR(20), @ID INT
	SELECT @ID = ID_USU, @COD = NOM_USU, @POSI = POSICION FROM inserted
	IF(@POSI = 'Administrativo')
		BEGIN
			UPDATE A SET ID_USU = @ID FROM ADMINISTRATIVO A
			INNER JOIN EMPLEADO E
			ON A.ID_EMPLEADO = E.ID_EMPLEADO
			WHERE E.COD_EMPLE = @COD
		END
	ELSE
		IF(@POSI = 'Docente')
			BEGIN
				UPDATE M SET ID_USU = @ID FROM MAESTRO M
				INNER JOIN EMPLEADO E
				ON M.ID_EMPLEADO = E.ID_EMPLEADO
				WHERE E.COD_EMPLE = @COD
			END
		ELSE
			UPDATE ALUMNO SET ID_USU = @ID WHERE COD_ALUM = @COD
GO

create PROCEDURE INSER_USU
@COD VARCHAR(10),
@PASS VARCHAR(15),
@POSICION VARCHAR(15)
AS
	INSERT INTO USUARIO VALUES(@COD, @PASS, @POSICION)
GO

SELECT * FROM MAESTRO GO
SELECT * FROM USUARIO GO
select * from ALUMNO
EXEC INSER_USU 'BTORRES98', '123', 'Alumno' GO
EXEC INSER_USU 'RH98', '123', ''